services:
  postgres:
    image: postgres:17
    container_name: pedija-postgres
    environment:
      POSTGRES_DB: pedija
      POSTGRES_USER: pedija12
      POSTGRES_PASSWORD: pedija123

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
