spring.application.name=pedija

spring.datasource.url=jdbc:postgresql://localhost:5432/pedija
spring.datasource.username=pedija12
spring.datasource.password=pedija123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

security.jwt.secret=UGVkaUphLWp3dC1kZXYtc2VjcmV0LWtleS1jaGFuZ2UtbWUtbG9jYWw=
security.jwt.expiration-ms=3600000
